# Generated by Django 5.1.4 on 2026-04-03 12:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Node",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "node_type",
                    models.CharField(
                        choices=[
                            ("trigger", "Trigger"),
                            ("http", "HTTP Request"),
                            ("transform", "Transform"),
                            ("condition", "Condição"),
                            ("llm", "Agente LLM"),
                            ("email", "Email"),
                            ("delay", "Delay"),
                            ("output", "Output"),
                        ],
                        max_length=20,
                    ),
                ),
                ("label", models.CharField(max_length=100)),
                (
                    "config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Configuração específica do tipo de nó",
                    ),
                ),
                (
                    "position_x",
                    models.FloatField(
                        default=0, help_text="Posição X no canvas (pixels)"
                    ),
                ),
                (
                    "position_y",
                    models.FloatField(
                        default=0, help_text="Posição Y no canvas (pixels)"
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Run",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("running", "Executando"),
                            ("success", "Sucesso"),
                            ("failed", "Falhou"),
                            ("cancelled", "Cancelado"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "trigger_type",
                    models.CharField(
                        default="manual",
                        help_text="Como a execução foi disparada",
                        max_length=20,
                    ),
                ),
                (
                    "input_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Dados de entrada para o trigger",
                    ),
                ),
                (
                    "output_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Resultado final do workflow",
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("duration_ms", models.PositiveIntegerField(default=0)),
                ("error_message", models.TextField(blank=True, default="")),
                ("nodes_total", models.PositiveIntegerField(default=0)),
                ("nodes_completed", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Workflow",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Rascunho"),
                            ("active", "Ativo"),
                            ("paused", "Pausado"),
                            ("archived", "Arquivado"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("tags", models.JSONField(blank=True, default=list)),
                (
                    "canvas_state",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Posição do viewport (zoom, pan) para restaurar o editor",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="NodeExecution",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("running", "Executando"),
                            ("success", "Sucesso"),
                            ("failed", "Falhou"),
                            ("skipped", "Pulado"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("input_data", models.JSONField(blank=True, default=dict)),
                ("output_data", models.JSONField(blank=True, default=dict)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("duration_ms", models.PositiveIntegerField(default=0)),
                ("error_message", models.TextField(blank=True, default="")),
                ("execution_order", models.PositiveIntegerField(default=0)),
                (
                    "node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="flowforge.node",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="node_executions",
                        to="flowforge.run",
                    ),
                ),
            ],
            options={
                "ordering": ["execution_order"],
            },
        ),
        migrations.AddField(
            model_name="run",
            name="workflow",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="runs",
                to="flowforge.workflow",
            ),
        ),
        migrations.AddField(
            model_name="node",
            name="workflow",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nodes",
                to="flowforge.workflow",
            ),
        ),
        migrations.CreateModel(
            name="Edge",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source_handle",
                    models.CharField(
                        default="default",
                        help_text="Handle de saída (default, true, false para condition)",
                        max_length=20,
                    ),
                ),
                ("label", models.CharField(blank=True, default="", max_length=50)),
                (
                    "source_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_edges",
                        to="flowforge.node",
                    ),
                ),
                (
                    "target_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_edges",
                        to="flowforge.node",
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="edges",
                        to="flowforge.workflow",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "unique_together": {("source_node", "target_node", "source_handle")},
            },
        ),
    ]
